dist: trusty
sudo: false
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
#     - llvm-toolchain-trusty-5.0
    packages:
      - g++-6
#     - clang-5.0

script:
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6
# - CXX=/usr/bin/clang++-5.0 CC=/usr/bin/clang-5.0
  - cmake ..
  - make && make test
